# Use postgres/example user/password credentials
version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: HealthConnect    
    ports:
      - "5432:5432"





#       # filepath: /C:/Menna/grad project/New folder/docker-compose.yml
# version: "3.8"
# services:
#   app:
#     build: .
#     volumes:
#       - .:/app
#     command: npm run start
#     ports:
#       - "3000:3000"
#     depends_on:
#       - postgres

#   postgres:
#     image: postgres
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: HealthConnect
#     ports:
#       - "5432:5432"